require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - vendor/**/*
    - bin/**/*
    - node_modules/**/*

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 110

Style/Documentation:
  Exclude:
    - app/**/*
    - config/**/*
