require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - vendor/**/*
    - bin/**/*
    - node_modules/**/*

Metrics/LineLength:
  Max: 110
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Rails:
  Enabled: true

Style/Documentation:
  Exclude:
    - app/**/*
    - config/**/*
