development:
  clients:
    default:
      database: overwatch_heroes_development
      hosts:
        - <%= ENV.fetch('MONGO_HOST', 'localhost') %>:27017

test:
  clients:
    default:
      database: overwatch_heroes_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
     uri: <%= ENV['MONGODB_URI'] %>
     options:
       connect_timeout: 15
